### ISSUE TITLE
Issues with column widths if colspan is used

### ISSUE THREAD

**Issue by rf2001** [drmacro/wordinator#6] opened 2019-06-25 10:18 UTC
It looks like column widths are not calculated correctly when there are columns with colspan specified.
I'm attaching a simple swpx file with two tables. The first has a colspan in the first cell, the second is based on this same table but with no colspan (and correspondingly fewer columns). Note that the first table is just a subset of a much larger table, but I've commented all body rows except the first to keep it short.
The second table has the first column of the correct width.
The first table should be the exactly the same but because of colspan the first column (spanned) is much too narrow.
[test.swpx.zip](https://github.com/drmacro/wordinator/files/3324746/test.swpx.zip)

**Comment by drmacro** [comment] 2019-06-25 15:35
Investigating. 

However, the table markup that gets generated simply uses the specified percentages directly in the word table without modification, so it seems very likely that this is either incorrect markup or a Word issue.

I would recommend turning on borders in the table so it's clear what the cell boundaries are.

**Comment by rf2001** [comment] 2019-06-26 07:40
It looks like the issue is colspan is not considered when calculating the column width, it just uses the width defined in the corresponding col. For the first table cols are defined like this:

`<cols>
	<col colwidth="4%"/>
	<col colwidth="4%"/>
	<col colwidth="20%"/>
	<col colwidth="2%"/>
	<col colwidth="12%"/>
	...
`
And the corresponding widths in docx are:

`<w:tcW w:type="pct" w:w="200"/>
<w:tcW w:type="pct" w:w="200"/>
<w:tcW w:type="pct" w:w="1000"/>
<w:tcW w:type="pct" w:w="100"/>
<w:tcW w:type="pct" w:w="600"/>
`
But the first cell spans three columns and its width should be 1400 (200 + 200 + 1000), and the second cell's width should be 100 (calculated from fourth col's width due to colspan in the preceding cell) and not 200 (calculated  from second col's width).

**Comment by drmacro** [comment] 2019-06-29 21:51
Should be fixed in latest code. 
Turned out to be easier than I thought--just need to set the "gridspan" property on the cell equal to the colspan value.

**Comment by rf2001** [comment] 2019-07-02 10:37
This is still not correct. In the sample table you attached it happens to be correct because the table has only four columns and though the width of the fourth column is wrong it doesn't matter as it's the last and it's automatically widen to fill the table width. Note that the second cell in the first row has w:w="500" (i.e. 10%) while it should be "3000" (i.e. 60%).
When you set the width of a non-spanned column you need to get the width of the correct col element. The index of the col element must be calculated as follows (conceptually), supposing the context is the current td which we are setting the width for: sum( preceding-sibling::*/@colspan ) + count( preceding-sibling::*[ not( @colspan) ]. This will give index=3 for the second td if the first entry has @colspan="3". I'm assuming Java code with 0 based indexes otherwise + 1 is needed of course.
You can use the attached swpx for testing.
[test.swpx.zip](https://github.com/drmacro/wordinator/files/3349608/test.swpx.zip)

**Comment by drmacro** [comment] 2019-07-09 03:11
I have pushed an update that calculates the percentage width of column-spanning cells when all the widths of the columns involved are percentages.

This appears to produce the correct width value (i.e., 1400 (28%) for the first cell in the first header row. This is confirmed in Word by using the Table Properties dialog to get the preferred width of the cell--Word reports 28%

However, in my tests this does not change the width of the columns as laid out by Word and there's no obvious reason why. I suspect it's something to do with cells with empty content. I tried putting in spaces and nbsp but it appeared to make no difference. At one point I put text in the narrow empty cells just to verify the column numbers and that changed it but I couldn't reproduce so not sure what the actual variable was.

I also implemented a new attribute on <td>, @shade, that takes a 6-digit hex color number (e.g., FFFF00) to set the shading color for a cell.

I used this to help debug the spans and so on, but it was needed anyway.

I think that the Word table being generated for your test table matches the original in terms of specified geometry but Word is not rendering it as expected. But I don't think that's a Wordinator problem unless we can identify some non-obvious property that, if set, will produce the correct result.

**Comment by rf2001** [comment] 2019-07-09 13:33
The problem is the column widths after the one with colspan are not calculated correctly. You are not calculating the correct col index as described in my previous comment. I'm attaching a zip containing the fixed docx (I've fixed it manually) and a text file with the correct column widths for all three rows in the first table in test.swpx. In parentheses you can see the values actually calculated by Wordinator. It's quite obvious what's going on. For example the width of the second column in the first row should be 100 (2%) but it is 200 (4%). That's because you are getting cols[ 1 ] width instead of cols[ 3 ] (indexes are zero-based).
Similarly, in the second row you are getting cols[ 1 ] instead of cols[ 3 ] and then cols[ 2 ] instead of cols[ 4 ].
The last row is all scrambled due to colspan=4 which, being even, actually swaps alternating 100 and 600 values in the following columns. So in this row is even more evident that wrong widths are taken.
To fix this you simply must calculate the col index as described above in my previous comment. Note that in general any number of mixed spanned and non-spanned cells can be present in a row and this must be considered when calculating the col index to use for the current column width. Obviously, the spanned column width is the sum of the widths, but you are calculating this already. The only issue seems to be the width of non-spanned cells AFTER one or more spanned cells.
[test.zip](https://github.com/drmacro/wordinator/files/3373183/test.zip)

**Comment by drmacro** [comment] 2019-07-11 12:23
Of course you are right--silly bug. Will fix.

**Comment by drmacro** [comment] 2019-07-11 12:35
[test.docx](https://github.com/drmacro/wordinator/files/3381984/test.docx)

The generated tables now look correct to me. You should be able to use table styles to control the font size in the table, which clearly needs to be smaller.

**Comment by drmacro** [comment] 2019-07-19 14:33
Verified.

**Closed by drmacro** 2019-07-19 14:33 UTC
Labels: bug
