### ISSUE TITLE
Refreshing fields truncates ToC entry text and invalidates hyperlinks

### ISSUE THREAD

**Issue by gkholman** [drmacro/wordinator#152] opened 2024-06-26 00:21 UTC
Data sent to Eliot by email due to the use of a proprietary stylesheet.

The image Before-Ctrl-A-F9.png shows the content created by Wordinator before pressing Ctrl-A and F9.
![Before-Ctrl-A-F9](https://github.com/drmacro/wordinator/assets/1319773/a895e273-a31d-43b2-a3c2-5c6ecb002761)

The image After-Ctrl-A-F9.png shows the content after pressing Ctrl-A and F9 with the following issues:
![After-Ctrl-A-F9](https://github.com/drmacro/wordinator/assets/1319773/a8ebca92-b141-4b3e-829b-cf25143e343c)

- the ToC text for Annex A is truncated (section 8 is unaffected)

- the ToC text for the Bibliography is replaced with the table's first row's first cell contents
- the hyperlink is invalid (and it looked okay but didn't work before the update of the content)

Reported earlier is the last line of the last paragraph of a section is justified when it shouldn't be, both before and after the update.

**Comment by ekimbernow** [comment] 2024-06-30 14:39
The last line justification issue is corrected in the latest build of 1.2.0--the fix was to eliminate the "compatibility mode". With compatibility mode no longer in effect, Word correctly renders the last paragraphs sections when justification is in effect.

**Comment by ekimbernow** [comment] 2024-06-30 14:53
Using my local build of 1.2.0, I get this result for the last paragraphs:

![image](https://github.com/drmacro/wordinator/assets/89863062/09222450-fbee-40ba-ac45-8c611e296b33)

**Comment by ekimbernow** [comment] 2024-06-30 14:54
This is the command I ran to generate the above:

```
java -jar target/wordinator-1.2.0-jar-with-dependencies.jar -i /Users/eliot.kimber/temp/gholman-wordinator/WordinatorIssue152/Holman-20240625/Holman-20240625.swpx -t /Users/eliot.kimber/temp/gholman-wordinator/WordinatorIssue152/Holman-20240625/Core-template.dotx -o ~/temp/gholman-wordinator/out
+ 2024-06-30 09:52:16,477 [INFO ] Input document or directory='/Users/eliot.kimber/temp/gholman-wordinator/WordinatorIssue152/Holman-20240625/Holman-20240625.swpx'
+ 2024-06-30 09:52:16,478 [INFO ] Output directory           ='/Users/eliot.kimber/temp/gholman-wordinator/out'
+ 2024-06-30 09:52:16,479 [INFO ] DOTX template              ='/Users/eliot.kimber/temp/gholman-wordinator/WordinatorIssue152/Holman-20240625/Core-template.dotx'
+ 2024-06-30 09:52:16,479 [INFO ] XSLT template              =Not specified
+ 2024-06-30 09:52:16,479 [INFO ] Catalog                    =Not specified
+ 2024-06-30 09:52:16,479 [INFO ] Chunk level                ='root'
+ 2024-06-30 09:52:16,918 [INFO ] Generating DOCX file "/Users/eliot.kimber/temp/gholman-wordinator/out/Holman-20240625.docx"
+ 2024-06-30 09:52:17,249 [INFO ] DOCX file generated.
```

**Comment by ekimbernow** [comment] 2024-06-30 14:57
For this hyperlink:
![image](https://github.com/drmacro/wordinator/assets/89863062/fbacf8ec-1685-4e57-a344-d40de1a79c9b)

The link works for me in the latest build.

**Comment by ekimbernow** [comment] 2024-06-30 14:59
For the Bibliography ToC entry, the issue seems to be that the bookmark ID "sec_bibl" is used both for the Bibliography title paragraph and in the following table:
```
        <wp:p style="Ref List Back Heading">
          <wp:bookmarkStart id="sec_bibl" name="sec_bibl"/>
          <wp:run>Bibliography</wp:run>
          <wp:bookmarkEnd id="sec_bibl"/>
        </wp:p>
        <wp:table style="Table Frame" layout="auto" frame="none" colsep="0" rowsep="0">
          <wp:tbody>
            <wp:tr>
              <wp:td valign="top" align="justify">
                <wp:p style="Body Text">
                  <wp:bookmarkStart id="__top" name="__top"/>
                  <wp:bookmarkStart id="__Realta_HTML_d4e4747" name="__Realta_HTML_d4e4747"/>
                  <wp:bookmarkStart id="sec_bibl" name="sec_bibl"/>
                  <wp:bookmarkStart id="ref_5" name="ref_5"/>
                  <wp:run>[1]</wp:run>
                  <wp:bookmarkEnd id="ref_5"/>
                  <wp:bookmarkEnd id="sec_bibl"/>
                  <wp:bookmarkEnd id="__Realta_HTML_d4e4747"/>
                  <wp:bookmarkEnd id="__top"/>
                </wp:p>
```
If I remove the second sec_bibl bookmark elements from the table then the update of the Bibliograph field in the ToC is correct (text "Bibliography") is retained.

**Comment by ekimbernow** [comment] 2024-06-30 15:06
It's the same issue for the Annex A ToC entry: The bookmark "sec_A" is used twice and Word reflects the second occurrence when it updates the field.

I gave the hidden paragraph a distinct bookmark name (sec_A_composed) and then the update works as expected:

![image](https://github.com/drmacro/wordinator/assets/89863062/a6d82389-9fa6-46ae-ab85-29eb9f4372d4)

**Comment by ekimbernow** [comment] 2024-06-30 15:07
[Holman-20240625.docx](https://github.com/user-attachments/files/16045136/Holman-20240625.docx)
[Holman-20240625.swpx_bookmarks_fixed.zip](https://github.com/user-attachments/files/16045138/Holman-20240625.swpx_bookmarks_fixed.zip)

Here's the Word I generated using the updated SWPX file.

I think all the reported issues are either resolved in 1.2.0 or a result of easily-correctible markup issues.

**Comment by gkholman** [comment] 2024-06-30 16:40
Ouch! Thank you, Eliot. This has revealed a fault in our validation that I was relying on.

I apologize for taking from your time on this non-issue. Thank you for being patient with me.

**Comment by ekimbernow** [comment] 2024-07-02 00:48
No worries at all—it was a subtle issue.

Have you worked out the issue with the XSLT transform?

Cheers,

E.

_____________________________________________
Eliot Kimber
Sr Staff Content Engineer
Digital Content & Design
O: 512 554 9368
M: 512 554 9368
servicenow.com<https://www.servicenow.com>
LinkedIn<https://www.linkedin.com/company/servicenow> | Twitter<https://twitter.com/servicenow> | YouTube<https://www.youtube.com/user/servicenowinc> | Facebook<https://www.facebook.com/servicenow>

From: G. Ken Holman ***@***.***>
Date: Sunday, June 30, 2024 at 9:40 AM
To: drmacro/wordinator ***@***.***>
Cc: Eliot Kimber ***@***.***>, Comment ***@***.***>
Subject: Re: [drmacro/wordinator] Refreshing fields truncates ToC entry text and invalidates hyperlinks (Issue #152)
[External Email]

________________________________
Ouch! Thank you, Eliot. This has revealed a fault in our validation that I was relying on.

I apologize for taking from your time on this non-issue. Thank you for being patient with me.

**Comment by gkholman** [comment] 2024-07-02 01:36
Thank you for understanding.

The JAR I've been using was created by Lars Marius and I'm guessing that it incorporates the stylesheet in some manner. 

When he returns he will be looking at the assembly and giving me more information. He built the jar to incorporate his pull requests that were needed by the client.

Have a great holiday! Today is Canada Day and our holiday.

**Comment by ekimbernow** [comment] 2024-08-04 19:28
Closing as not a bug.

**Closed as completed by ekimbernow** 2024-08-04 19:28 UTC
