### ISSUE TITLE
Table rows have lots of space above and below

### ISSUE THREAD

**Issue by rf2001** [drmacro/wordinator#4] opened 2019-06-21 13:15 UTC
I'm not sure this is a Wordinator issue, maybe it can be somehow fixed with a different template. But in case it's worth a check.

I'm attaching a docx file generated from the swpx attached to issue (2).

The TOC on page 1 is generated as a table. Note how far apart the text in rows is. Have no idea how to make the rows less high.

If you check the table on page 30, it's even worse. It has three rows ("ILLUSTRATIVE EXAMPLES", "APPENDIX", "Amendments to the guidance on other IFRSs") which are far apart. 

Any suggestion as how this may be fixed is welcomed (either in swpx or in dotx).
[bv-ifrs13.docx](https://github.com/drmacro/wordinator/files/3314609/bv-ifrs13.docx)

**Comment by drmacro** [comment] 2019-06-22 17:35
Investigating

**Comment by drmacro** [comment] 2019-06-22 17:56
The issue seems to be that the styles for the paragraphs within the cells have explicit space before and after.

If I change those to 0pt then the table is as compact as possible.

For example, the style on the page number column paragraphs had a space-before of 6pts.

Unlike XSL-FO, space before and space after is not collapsed at the start or end of a block, as far as I can tell.

**Comment by drmacro** [comment] 2019-06-22 17:56
Closing as not a bug. I was able to resolve the formatting issue by changing only the style definition.

**Comment by mikeewins** [comment] 2019-06-24 08:49
Hi Eliot,

This appears to be more than the style definition so I'm adding extra information.

Regards,

Mike
[Issue_4_questions.pdf](https://github.com/drmacro/wordinator/files/3320002/Issue_4_questions.pdf)

**Comment by drmacro** [comment] 2019-06-24 11:59
As far as I can tell this is not an issue with the table markup as generated--that is, Wordinator and POI are not doing anything special with the table.

If you inspect the styles applied to the paragraphs in the cells there is definitely space before and after defined for those and that definitely contributes to the overall row vertical space.

In addition, if you apply one of the predefined table layouts you are applying a table style. Comparing the table markup before and after doing that the only significant difference I can see is the reference to the table style.

So it must be the table style that is affecting/controlling the effective vertical size of the rows.

Creating a new table style and doing nothing other than applying it changes the table layout, reducing the vertical table space. This feels like a Word bug to me but the effect is easy to demonstrate.

I've attached a copy of bv-ifrs13 to which the only thing I did was create a new table style and apply it to the table. I did not modify the table style in any way.

[bv-ifrs13-table-style.docx](https://github.com/drmacro/wordinator/files/3320661/bv-ifrs13-table-style.docx)

**Comment by mikeewins** [comment] 2019-06-24 12:08
Thanks Eliot.

Is it possible to apply a Table Style in the conversion? Just wondering if a Table Style were purposefully applied it would resolve this issue.

Regards,

Mike

**Comment by drmacro** [comment] 2019-06-24 14:07
I'm implementing support for using table styles and also refining how borders are set at the table and cell level--current code is setting explicit values when it should not, blocking settings from styles. It may take me a day or two to get this worked out but that should then enable resolving the table layout issue by creating appropriate table styles.

**Closed** 2019-06-26 06:38 UTC
Labels: bug, enhancement
